"""Generate the six Table 8 configurations, so their layer indices cannot drift.

    python ablation/make_ablation_configs.py

Each row adds one component to the previous, and every `from` index is computed from
the layer list rather than written by hand: inserting an attention block shifts every
index after it, which is exactly the kind of silent error that produced the published
table's `bifpn_only.yaml` (no BiFPN in it, and a detect head wired to the wrong layers).

Rows 5 and 6 replace C2PSA with a 1x1 convolution because the trained model does, so
they differ from rows 1-4 in two respects rather than one. That confound belongs in
the table caption; it is not something the configuration can avoid without departing
from what was actually trained.
"""

from __future__ import annotations

import sys
from pathlib import Path

SCALES = """scales:
  n: [0.50, 0.25, 1024]
  s: [0.50, 0.50, 1024]
  m: [0.50, 1.00, 512]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.50, 512]"""

# (module, args, note) — 'from' is always the previous layer here
BACKBONE = [
    ("Conv", "[64, 3, 2]", "P1/2"), ("Conv", "[128, 3, 2]", "P2/4"),
    ("C3k2", "[256, False, 0.25]", ""), ("Conv", "[256, 3, 2]", "P3/8"),
    ("C3k2", "[512, False, 0.25]", "P3 tap"), ("Conv", "[512, 3, 2]", "P4/16"),
    ("C3k2", "[512, True]", "P4 tap"), ("Conv", "[1024, 3, 2]", "P5/32"),
    ("C3k2", "[1024, True]", ""), ("SPPF", "[1024, 5]", ""),
]
P3_TAP, P4_TAP = 4, 6


def build(name: str, title: str, *, bifpn: bool, cbam: str | None,
          cross_attention: bool) -> str:
    """Assemble one configuration, resolving every index as the list is built."""
    lines = [f"# Table 8: {title}"]
    if cross_attention:
        lines.append("# C2PSA is replaced by a 1x1 Conv, as in the trained model.")
    lines += [f"# Generated by make_ablation_configs.py; do not hand-edit indices.",
              "nc: 8", SCALES, "", "backbone:"]

    for module, args, note in BACKBONE:
        lines.append(f"  - [-1, 1, {module}, {args}]" + (f"  # {note}" if note else ""))
    tail = ("Conv", "[1024, 1, 1]") if cross_attention else ("C2PSA", "[1024]")
    lines.append(f"  - [-1, {1 if cross_attention else 2}, {tail[0]}, {tail[1]}]  # P5")

    # `base` is fixed: the index of the last backbone layer, from which head indices
    # are counted. `p5_src` moves when cross-attention replaces P5 as the source the
    # bottom-up path concatenates. Conflating the two shifts every later index by one.
    base = len(BACKBONE)
    p5_src = base

    head: list[tuple[str, str]] = []         # (yaml body, comment)

    def emit(body: str, comment: str = "") -> int:
        head.append((body, comment))
        return base + len(head)              # index of the layer just added

    if cross_attention:
        p5_src = emit(f"[[{P4_TAP}, {base}], 1, CrossAttentionBlock, [1024, 512]]",
                      "Q from P5, K/V from P4")

    emit('[-1, 1, nn.Upsample, [None, 2, "nearest"]]')
    emit(f"[[-1, {P4_TAP}], 1, Concat, [1]]")
    p4_td = emit("[-1, 2, C3k2, [512, False]]", "P4 top-down")

    emit('[-1, 1, nn.Upsample, [None, 2, "nearest"]]')
    emit(f"[[-1, {P3_TAP}], 1, Concat, [1]]")
    p3 = emit("[-1, 2, C3k2, [256, False]]", "P3 top-down")
    if cbam:
        p3 = emit(f"[-1, 1, {cbam}, [256, 16]]", "P3/8-small")

    emit("[-1, 1, Conv, [256, 3, 2]]")
    emit(f"[[-1, {p4_td}, {P4_TAP}], 1, Concat, [1]]" if bifpn
         else f"[[-1, {p4_td}], 1, Concat, [1]]", "tri-input" if bifpn else "")
    p4 = emit("[-1, 2, C3k2, [512, False]]")
    if cbam:
        p4 = emit(f"[-1, 1, {cbam}, [512, 16]]", "P4/16-medium")

    emit("[-1, 1, Conv, [512, 3, 2]]")
    emit(f"[[-1, {p5_src}], 1, Concat, [1]]")
    p5_out = emit("[-1, 2, C3k2, [1024, True]]")
    if cbam:
        p5_out = emit(f"[-1, 1, {cbam}, [1024, 16]]", "P5/32-large")

    emit(f"[[{p3}, {p4}, {p5_out}], 1, OBB, [nc, 1]]")

    lines.append("")
    lines.append("head:")
    for n, (body, comment) in enumerate(head, start=len(BACKBONE) + 1):
        lines.append(f"  - {body}".ljust(52) + f"# {n}" + (f" {comment}" if comment else ""))
    return "\n".join(lines) + "\n"


ROWS = [
    ("a1_stock", "row 1, stock YOLOv11s-OBB",
     dict(bifpn=False, cbam=None, cross_attention=False)),
    ("a2_bifpn", "row 2, plus a BiFPN neck",
     dict(bifpn=True, cbam=None, cross_attention=False)),
    ("a3_bifpn_stdcbam", "row 3, plus standard CBAM, single 7x7 spatial kernel",
     dict(bifpn=True, cbam="StandardCBAM", cross_attention=False)),
    ("a4_bifpn_mscbam", "row 4, plus MS-CBAM, parallel 3/5/7 spatial kernels",
     dict(bifpn=True, cbam="MultiScaleCBAM", cross_attention=False)),
    ("a5_bifpn_crossattn", "row 5, plus cross-attention, no CBAM",
     dict(bifpn=True, cbam=None, cross_attention=True)),
]


def main() -> int:
    out = Path(__file__).parent / "configs"
    for name, title, opts in ROWS:
        (out / f"{name}.yaml").write_text(build(name, title, **opts), encoding="utf-8")
        print(f"wrote {name}.yaml")
    print("row 6 is full_legacy.yaml, the deployed model, already present")
    return 0


if __name__ == "__main__":
    sys.exit(main())
